[package]
name = "single_threaded_server"
version = "0.1.0"
edition = "2024"

[dependencies]
matchit = "0.8.6"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_urlencoded = "0.7.1"
thiserror = "2.0.17"
